import Head from 'next/head';
import React from 'react';
import { FaAtom, FaCss3, FaGit, FaGithub, FaHtml5, FaJs, FaPython, FaReact } from 'react-icons/fa';
import { SiTailwindcss } from 'react-icons/si';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Image from 'next/legacy/image';
import devimg from './../../public/assets/devimg.png'
import { useState } from 'react';
import flip1 from './../../public/ecommerce/flip1.png';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Shrish Kerur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='px-4 min-h-screen md:px-16 dark:bg-gray-900'>
        <section className='px-3'>
          <nav className='py-10 flex justify-between items-center'>
            <h3 className='text-[16px] text-gray-700 font-medium md:text-4xl dark:text-gray-300'>Shrish Kerur</h3>

            <ul className='flex items-center text-lg'>
              <li className='mx-8 text-gray-700 md:mx-12'>
                <button className='p-3 rounded-full dark:bg-slate-100'>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='dark:bg-slate-100' />
                </button>
              </li>
              <li><a className='bg-teal-500 text-gray-700 font-medium px-3 py-1 rounded-md md:px-6 md:py-3' href='#'>Resume</a></li>
            </ul>
          </nav>
        </section>



        <section className='px-3 py-16 h-full text-center md:flex md:justify-center md:items-center'>
          <div className='text-center md:w-3/5 md:text-left'>
            <h2 className='my-3 text-4xl text-gray-700 md:text-5xl dark:text-gray-300'>Hai I am Shrish</h2>
            <span className='text-2xl text-teal-700 font-medium md:text-3xl dark:text-teal-400'>A Front End Developer</span>
            <p className='my-8 text-xl text-gray-700 md:text-2xl dark:text-gray-300'>I am a passionate Front-End Web Developer. Having good knowledge of JavaScript, React and tailwindcss. I keep sharing about my learning on twitter, and I also write blogs on hashnode. You can have a look at all of my projects and source code on my GitHub account. You can also say a hai to me down below.</p>
          </div>

            <div className='relative bg-gradient-to-b from-teal-500 py-6 mx-auto w-60 h-60 rounded-full overflow-hidden md:w-96 md:h-96 md:px-10'>
              <Image 
                layout='fill'
                objectFit='cover'
                src={devimg}
                alt="logo"
                sizes={180}
              />
            </div>
        </section>




        <section className='px-3 py-16 h-full text-center'>
          <div className='my-12'>
            <h3 className='mx-auto py-4 text-4xl text-teal-700 font-medium md:text-6xl dark:text-teal-400'>Services</h3>
          </div>

          <div className='py-2 grid grid-cols-2 grid-rows-2 gap-8 md:grid-cols-4 md:gap-24 dark:text-gray-300'>
            <div className='px-4 mx-auto w-46 h-32 text-2xl text-yellow-500 font-medium dark:text-yellow-400'><FaJs size={90} />JavaScript</div>
            <div className='px-4 mx-auto w-46 h-32 text-2xl text-cyan-400 font-medium dark:text-cyan-600'><FaReact size={90} />React</div>
            <div className='px-4 mx-auto w-46 h-32 text-2xl text-blue-600 font-medium dark:text-blue-600'><FaCss3 size={90} />CSS</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl text-yellow-400 font-medium dark:text-yellow-400'><FaPython size={90} />Python</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl text-orange-600 font-medium dark:text-orange-700'><FaGit size={90} />Git</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl text-sky-600 font-medium dark:text-sky-700'><SiTailwindcss size={90} />tailwindcss</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl text-orange-500 font-medium dark:text-orange-500'><FaHtml5 size={90} />HTMl</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl text-green-500 font-medium text-green-500'><FaAtom size={90} />Atom</div>
          </div>

        </section>

        <section className='px-3 py-16 h-full text-center'>
            <div className='mx-auto my-6'>
              <h3 className='text-4xl text-teal-700 font-medium md:text-6xl md:py-4 dark:text-teal-400'>Work</h3>
            </div>

          <div className='grid grid-cols-1 gap-8 md:grid-cols-3 md:justify-items-center'>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-2xl text-gray-800 font-semibold md:text-2xl'>Portfolio Project</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12 relative'>
              <div>
                <Image 
                  src={flip1}
                  className='blur-[0.03rem] hover:blur-none rounded-t-2xl'
                  // layout='fill'
                  objectFit='cover'
                />
              </div>
              <span className='text-2xl text-black font-semibold md:text-2xl'>e-Commerce Project</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-2xl text-gray-800 font-semibold md:text-2xl'>Personal Landing Page</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-2xl text-gray-800 font-semibold md:text-2xl'>To-Do App</span>
            </div>

            
            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-2xl text-gray-800 font-semibold md:text-2xl'>To-Do App</span>
            </div>


            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-2xl text-gray-800 font-semibold md:text-2xl'>To-Do App</span>
            </div>

          </div>
        </section>


      <section className='px-3 py-16 text-center'>
        <div className='w-full md:w-3/5 md:mx-auto'>

          <h3 className='mx-auto my-12 text-4xl text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Say a Hai</h3>

          <div>
            <form action='https://getform.io/f/c4401388-b490-4748-a9ce-0d431669dbe4' method='POST'>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <input name='name' className='my-2 px-4 py-3 w-full rounded-lg bg-teal-200 md:h-12 dark:bg-teal-600 dark:text-gray-200' type={'text'} /><span className='text-2xl px-3 md:text-3xl dark:text-gray-200'>Name</span>
            </div>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <input name='email' className='my-2 px-4 py-2 w-full rounded-lg bg-teal-200 md:h-12 dark:bg-teal-600 dark:text-gray-200' type={'email'} /><span className='text-2xl px-3 md:text-3xl dark:text-gray-200'>Email</span>
            </div>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <textarea name='comment' className='my-2 px-4 py-2 w-full rounded-lg bg-teal-200 h-64 dark:bg-teal-600 dark:text-gray-200' type={'text'} /><span className='text-2xl px-3 md:text-3xl dark:text-gray-200'>Comment</span>
            </div>
            
            <div>
              <button className='my-8 px-8 py-4 text-3xl bg-teal-400 border-none rounded-lg'>Submit</button>
            </div>
            
            </form>
          </div>

          <div className='w-full mx-auto my-10'>
            <h2 className='text-4xl text-teal-600 md:text-7xl dark:text-teal-400'>Thank You 🙏</h2>
          </div>
          
        </div>
      </section>

      </main>
    </div>
  );
}
